services:
  folderhost:
    image: mertjsx/folderhost:latest
    container_name: folderhost-server
    ports:
      - "5000:5000"  # Change to match your config.yml port
    volumes:
      - folderhost_data:/app
    restart: unless-stopped
    
volumes:
  folderhost_data: