services:
  folderhost:
    container_name: folderhost-server
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./database.db:/folderhost-server/database.db:z
      - ./recovery_bin:/folderhost-server/recovery_bin:z
      - ./testdir:/folderhost-server/host:z
      - ./config.yml:/folderhost-server/config.yml:z
    restart: unless-stopped
  folderhost-client: # Service name
    container_name: folderhost-client
    build: 
      context: ./web # Dockerfile path
    ports:
      - "5173:5173"
    volumes:
      - ./web/src:/folderhost-client/src:z
      - ./web/index.html:/folderhost-client/index.html:z
      - ./web/public:/folderhost-client/public:z
    restart: unless-stopped